#!/bin/bash

source installation_settings.sh

mkdir -p ${PYTHONOCC_BUILD_DIR}
cd ${PYTHONOCC_BUILD_DIR}

cmake ${PYTHONOCC_SOURCES_DIR} \
    -DCMAKE_INSTALL_PREFIX:PATH=${PYTHONOCC_INSTALL_DIR}/OCC \
    -DPYTHONOCC_INSTALL_DIRECTORY:PATH=${PYTHONOCC_INSTALL_DIR}/OCC \
    -DOCE_INCLUDE_PATH:PATH=${OCE_INSTALL_DIR}/include/oce \
    -DOCE_LIB_PATH:PATH=${OCE_INSTALL_DIR}/lib/ \
    -DPYTHONOCC_WRAP_SMESH:BOOL=ON \
    -DPYTHONOCC_WRAP_NETGEN:BOOL=ON \
    -DSMESH_INCLUDE_PATH:PATH=${SMESH_INSTALL_DIR}/include/smesh \
    -DSMESH_LIB_PATH:PATH=${SMESH_INSTALL_DIR}/lib/x86_64-linux-gnu \
    -DSWIG_EXECUTABLE:FILEPATH=${SWIG_EXECUTABLE} \
    -DSWIG_DIR:PATH=${SWIG_SHARE} \
    -DSWIG_VERSION:STRING=${SWIG_VERSION}

make -j${NUMBER_OF_CPUS} && make install
